-- DarumTech Intra v2 Schema
-- Run order matters due to FK constraints

CREATE TABLE DEPARTMENT (
    DEPTNO    BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DEPT_NAME VARCHAR(100) NOT NULL,
    DEPT_RANK INTEGER,
    PRIMARY KEY (DEPTNO)
);

CREATE TABLE JOBGRADE (
    JOBNO    BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    JOB_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (JOBNO)
);

-- NOTE: POSITION is a reserved word in DB2, using double quotes
CREATE TABLE "POSITION" (
    POSTNO    BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    POST_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (POSTNO)
);

CREATE TABLE EMPLOYEE (
    EMPNO      BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID         VARCHAR(50)  NOT NULL,
    PW         VARCHAR(255) NOT NULL,
    NAME       VARCHAR(100) NOT NULL,
    MAIL       VARCHAR(100),
    PHONE      VARCHAR(20),
    DEPTNO     BIGINT,
    JOBNO      BIGINT,
    POSTNO     BIGINT,
    ENTRY_DATE DATE,
    LEAVE_DATE DATE,
    INTRA_VIEW BOOLEAN      NOT NULL DEFAULT TRUE,
    EMP_STATE  BOOLEAN      NOT NULL DEFAULT TRUE,
    PERMISSION VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',
    PRIMARY KEY (EMPNO),
    CONSTRAINT UQ_EMP_ID    UNIQUE (ID),
    CONSTRAINT FK_EMP_DEPT  FOREIGN KEY (DEPTNO)  REFERENCES DEPARTMENT(DEPTNO),
    CONSTRAINT FK_EMP_JOB   FOREIGN KEY (JOBNO)   REFERENCES JOBGRADE(JOBNO),
    CONSTRAINT FK_EMP_POST  FOREIGN KEY (POSTNO)  REFERENCES "POSITION"(POSTNO)
);

CREATE TABLE CUSTOMER (
    CUSTNO     BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CUST_NAME  VARCHAR(100) NOT NULL,
    DARUM_SALES VARCHAR(100),
    VACATION   BOOLEAN      NOT NULL DEFAULT FALSE,
    LOCATION   VARCHAR(200),
    PRIMARY KEY (CUSTNO)
);

CREATE TABLE PRODUCT (
    PRODNO     BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    PROD_NAME  VARCHAR(100) NOT NULL,
    PROD_STATE BOOLEAN      NOT NULL DEFAULT TRUE,
    VACATION   BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (PRODNO)
);

CREATE TABLE SUPPORT (
    SUPPNO   BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SUPPNAME VARCHAR(100) NOT NULL,
    VACATION BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (SUPPNO)
);

CREATE TABLE SCHEDULE (
    NO        BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    EMPNO     BIGINT       NOT NULL,
    CUSTNO    BIGINT,
    PRODNO    BIGINT,
    SUPPNO    BIGINT,
    CONTENTS  VARCHAR(500),
    LOCATION  VARCHAR(200),
    WORK_DATE DATE         NOT NULL,
    STIME     TIME,
    RTIME     TIME,
    ETIME     TIME,
    START_NO  BIGINT       NOT NULL DEFAULT 0,
    HOLIDAY   BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (NO),
    CONSTRAINT FK_SCHED_EMP  FOREIGN KEY (EMPNO)  REFERENCES EMPLOYEE(EMPNO),
    CONSTRAINT FK_SCHED_CUST FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO),
    CONSTRAINT FK_SCHED_PROD FOREIGN KEY (PRODNO) REFERENCES PRODUCT(PRODNO),
    CONSTRAINT FK_SCHED_SUPP FOREIGN KEY (SUPPNO) REFERENCES SUPPORT(SUPPNO)
);
