-- Seed Data for DarumTech Intra v2
-- Password for all users: "root" (BCrypt cost 10)

-- DEPARTMENT
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('경영지원본부');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('전략기획사업부');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('사업1부');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('사업1부[TS1팀]');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('사업1부[TS2팀]');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('사업1부[TS3팀]');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('사업2부[TS1팀]');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('사업2부[TS2팀]');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('사업2부[TS3팀]');

-- JOBGRADE (직급): JOBNO 1~5
INSERT INTO JOBGRADE (JOB_NAME) VALUES ('사원');
INSERT INTO JOBGRADE (JOB_NAME) VALUES ('대리');
INSERT INTO JOBGRADE (JOB_NAME) VALUES ('과장');
INSERT INTO JOBGRADE (JOB_NAME) VALUES ('차장');
INSERT INTO JOBGRADE (JOB_NAME) VALUES ('부장');

-- POSITION (직책): POSTNO 1=팀원, 2=팀장
INSERT INTO "POSITION" (POST_NAME) VALUES ('팀원');
INSERT INTO "POSITION" (POST_NAME) VALUES ('팀장');

-- CUSTOMER
INSERT INTO CUSTOMER (CUST_NAME) VALUES ('메트라이프');
INSERT INTO CUSTOMER (CUST_NAME) VALUES ('삼성SDS');
INSERT INTO CUSTOMER (CUST_NAME) VALUES ('한국야쿠르트');
INSERT INTO CUSTOMER (CUST_NAME) VALUES ('셀트리온');

-- PRODUCT
INSERT INTO PRODUCT (PROD_NAME) VALUES ('Instana');
INSERT INTO PRODUCT (PROD_NAME) VALUES ('OCP');
INSERT INTO PRODUCT (PROD_NAME) VALUES ('DB2');

-- SUPPORT
INSERT INTO SUPPORT (SUPPNAME) VALUES ('MA');
INSERT INTO SUPPORT (SUPPNAME) VALUES ('SVC');

-- EMPLOYEE: admin (ROLE_SUPERADMIN, 부서/직급/직책 없음)
INSERT INTO EMPLOYEE (ID, PW, NAME, PERMISSION)
VALUES ('admin', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '관리자', 'ROLE_SUPERADMIN');

-- EMPLOYEE: test1~20
-- JOBNO: 1=사원, 2=대리, 3=과장, 4=차장, 5=부장
-- POSTNO: 1=팀원, 2=팀장 (부서별 첫번째 인원이 팀장)

-- 경영지원본부 (DEPTNO=1)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test1',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트1',  1, 3, 2, 'ROLE_ADMIN');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test2',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트2',  1, 1, 1, 'ROLE_USER');
-- 전략기획사업부 (DEPTNO=2)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test3',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트3',  2, 4, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test4',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트4',  2, 2, 1, 'ROLE_USER');
-- 사업1부 (DEPTNO=3)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test5',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트5',  3, 5, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test6',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트6',  3, 1, 1, 'ROLE_USER');
-- 사업1부[TS1팀] (DEPTNO=4)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test7',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트7',  4, 3, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test8',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트8',  4, 1, 1, 'ROLE_USER');
-- 사업1부[TS2팀] (DEPTNO=5)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test9',  '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트9',  5, 2, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test10', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트10', 5, 4, 1, 'ROLE_ADMIN');
-- 사업1부[TS3팀] (DEPTNO=6)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test11', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트11', 6, 3, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test12', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트12', 6, 2, 1, 'ROLE_USER');
-- 사업2부[TS1팀] (DEPTNO=7)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test13', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트13', 7, 5, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test14', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트14', 7, 2, 1, 'ROLE_USER');
-- 사업2부[TS2팀] (DEPTNO=8)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test15', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트15', 8, 4, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test16', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트16', 8, 1, 1, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test17', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트17', 8, 2, 1, 'ROLE_USER');
-- 사업2부[TS3팀] (DEPTNO=9)
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test18', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트18', 9, 3, 2, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test19', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트19', 9, 1, 1, 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, PW, NAME, DEPTNO, JOBNO, POSTNO, PERMISSION) VALUES ('test20', '$2a$10$KJkG6LNczKlSl7To5xmtwupH8drHwtz/u7ftriy8rlHGZnPmBaSf6', '테스트20', 9, 2, 1, 'ROLE_USER');
