apiVersion: apps/v1
kind: Deployment
metadata:
  name: intra-frontend
  namespace: intra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intra-frontend
  template:
    metadata:
      labels:
        app: intra-frontend
    spec:
      containers:
        - name: frontend
          image: darumtech/intra-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
