apiVersion: v1
kind: Secret
metadata:
  name: intra-backend-secrets
  namespace: intra
stringData:
  DB_URL: "jdbc:db2://192.168.0.70:25010/INTRA"
  DB_USERNAME: "db2inst1"
  DB_PASSWORD: "change-me"
  JASYPT_ENCRYPTOR_PASSWORD: "change-me"
